services:
  stirling-pdf:
    container_name: stirling-pdf
    image: stirlingtools/stirling-pdf:latest
    restart: unless-stopped
    # user: root  <-- LO QUITAMOS, dejamos que el script interno gestione el usuario
    ports:
      - "8081:8080"
    volumes:
      # Conectamos las carpetas que creamos en Termius
      - /opt/docker/stirling/configs:/configs
      - /opt/docker/stirling/logs:/logs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.entrypoints=web"
      - "traefik.http.routers.stirling-pdf.rule=Host(`pdf.vilcheztech.com`)"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
