services:
  stirling-pdf:
    container_name: stirling-pdf
    image: stirlingtools/stirling-pdf:latest
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - PUID=1000
      - PGID=1000
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.entrypoints=web"
      - "traefik.http.routers.stirling-pdf.rule=Host(`pdf.vilcheztech.com`)"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
