services:
  stirling-pdf:
    container_name: stirling-pdf
    image: stirlingtools/stirling-pdf:latest
    restart: unless-stopped
    # Forzamos ejecución como root para que no pida permiso al arrancar
    user: root
    ports:
      - "8081:8080"
    volumes:
      - /opt/docker/stirling/configs:/configs
      - /opt/docker/stirling/logs:/logs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      # Quitamos PUID/PGID para que no intente hacer cambios de usuario complejos que fallan
    # --- AQUÍ ESTÁ LA MAGIA PARA PROXMOX ---
    security_opt:
      - apparmor:unconfined
    # ---------------------------------------
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.entrypoints=web"
      - "traefik.http.routers.stirling-pdf.rule=Host(`pdf.vilcheztech.com`)"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
