services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    privileged: true
    security_opt:
      - apparmor:unconfined
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Lima
    volumes:
      - /data/jellyseerr_config:/app/config
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`pedir.vilcheztech.com`)"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    privileged: true
    security_opt:
      - apparmor:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
    volumes:
      - sonarr_config:/config
      - /mnt/pve/Disco4TB/media:/data
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.vilcheztech.com`)"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    privileged: true
    security_opt:
      - apparmor:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
    volumes:
      - radarr_config:/config
      - /mnt/pve/Disco4TB/media:/data
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.vilcheztech.com`)"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    privileged: true
    security_opt:
      - apparmor:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
    volumes:
      - bazarr_config:/config
      - /mnt/pve/Disco4TB/media:/data
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.vilcheztech.com`)"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    privileged: true
    security_opt:
      - apparmor:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
      - WEBUI_PORT=8080
    volumes:
      - qbit_config:/config
      - /mnt/pve/Disco4TB/media:/data     # <--- Destino final (HDD 4TB)
      - /data/downloads_temp:/incomplete  # <--- NUEVO: Puente (SSD 1TB)
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbit.rule=Host(`qb.vilcheztech.com`)"
      - "traefik.http.services.qbit.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    privileged: true
    security_opt:
      - apparmor:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
    volumes:
      - prowlarr_config:/config
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.vilcheztech.com`)"

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    privileged: true # PrevenciÃ³n de bloqueos de red
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    networks:
      - proxy

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    privileged: true
    security_opt:
      - apparmor:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
      - LIBVA_DRIVER_NAME=radeonsi
    volumes:
      - jellyfin_config:/config
      - /mnt/pve/Disco4TB:/data
      - /mnt/gopro_21_23:/media/gopro_21_23
      - /mnt/gopro_24_25_dji:/media/gopro_24_25_dji
    group_add:
      - "44"
      - "993"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.vilcheztech.com`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
    restart: unless-stopped
    networks:
      - proxy

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    pid: host
    privileged: true
    environment:
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.rule=Host(`monitor.vilcheztech.com`)"

volumes:
  jellyfin_config:
  qbit_config:
  sonarr_config:
  radarr_config:
  prowlarr_config:
  bazarr_config:
  jellyseerr_config:

networks:
  proxy:
    external: true
