services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    volumes:
      - /mnt/pve/Disco4TB/data/immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Usamos el nombre del SERVICIO, que es más seguro para DNS interno
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - DB_PORT=5432
      - REDIS_PORT=6379
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "2283:2283"
    depends_on:
      - immich-redis
      - immich-postgres
    restart: always
    networks:
      - internal  # Para hablar con la base de datos
      - proxy     # Para salir a internet vía Traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.entrypoints=web,websecure"
      - "traefik.http.routers.immich.rule=Host(`fotos.vilcheztech.com`)"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    volumes:
      - /mnt/pve/Disco4TB/data/immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - DB_PORT=5432
      - REDIS_PORT=6379
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - immich-redis
      - immich-postgres
    restart: always
    networks:
      - internal # Solo necesita red interna

  # Machine Learning DESACTIVADO por ahora
  # immich-machine-learning:
  #   container_name: immich_machine_learning
  #   image: ghcr.io/immich-app/immich-machine-learning:release
  #   volumes:
  #     - model-cache:/cache
  #   environment:
  #     - IMMICH_MACHINE_LEARNING_ACCELERATORS=cpu
  #   restart: always
  #   networks:
  #     - internal

  immich-redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    restart: always
    networks:
      - internal

  immich-postgres:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - internal

volumes:
  model-cache:
  postgres_data:

networks:
  internal: # Red privada para ellos
    driver: bridge
  proxy:    # Red pública para Traefik
    external: true
