services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    volumes:
      - /mnt/pve/Disco4TB/data/immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      # --- DATOS FIJOS (Hardcoded) ---
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - DB_PORT=5432
      - REDIS_PORT=6379
      # --- VARIABLES SECRETAS (Desde Portainer) ---
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "2283:2283"
    depends_on:
      - immich-redis
      - immich-postgres
    restart: always
    networks:
      - proxy
    devices:
      - /dev/dri:/dev/dri
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.entrypoints=web,websecure"
      - "traefik.http.routers.immich.rule=Host(`fotos.vilcheztech.com`)"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    volumes:
      - /mnt/pve/Disco4TB/data/immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      # --- DATOS FIJOS ---
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - DB_PORT=5432
      - REDIS_PORT=6379
      # --- VARIABLES SECRETAS ---
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - immich-redis
      - immich-postgres
    restart: always
    networks:
      - proxy
    devices:
      - /dev/dri:/dev/dri

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    restart: always
    networks:
      - proxy

  immich-redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:e3b1794e8e16a20923b3c41429e9d9b44274d4402636a8e803c2763327d6d9e0
    restart: always
    networks:
      - proxy

  immich-postgres:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Esta es la Ãºnica que necesita leer de Portainer
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - immich_postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - proxy

volumes:
  model-cache:
  immich_postgres_data:
    external: true
    name: immich_immich_postgres_data

networks:
  proxy:
    external: true
