services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: ryzen-server
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /opt/docker/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    # --- AQUÍ ESTÁ LA SOLUCIÓN ---
    privileged: true                 # Necesario para crear interfaces VPN
    user: "0:0"                      # Asegura que corra como root
    security_opt:
      - apparmor:unconfined          # Desactiva el bloqueo de seguridad
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    # -----------------------------
    restart: unless-stopped
    network_mode: host
